[package]
name = "dotfox"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "macros", "fs"] }
dirs = "5.0.1"
rayon = "1.7.0"
git2 = "0.17.1"
gpgme = { version = "0.11.0", features = ["v1_18"] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"