[package]
name = "dotfox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros","fs"] }
dirs = "4.0"
rayon = "1.5.3"
