on:
  push:
    branches:
      - mistress
    tags:
      - "v*.*.*"

name: Release Packaging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master@v4
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none

      - name: Upload arifacts
        id: upload
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/mistress'
        with:
          name: dotfox
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

      - name: Publish
        id: publishing
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
          draft: true
